name: ci
on:
  push:
    branches: ['*']
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: fabasoad/setup-cassandra-action@v1.0.0
      - run: yarn --frozen-lockfile
      - working-directory: ./electrode-ota-mariadb-schema
        run: |
          docker-compose build
          docker-compose up -d
          docker-compose exec ota-db /common/wait-for-it.sh -t 30 ota-db:3306
          docker-compose logs
      - run: yarn test
      - working-directory: ./electrode-ota-mariadb-schema
        run: docker-compose down
